'use server'
import { requireRole } from '@/lib/auth'
import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
const value=(f:FormData,k:string)=>String(f.get(k)??'').trim()
const fail=(p:string,m:string):never=>redirect(`${p}?error=${encodeURIComponent(m)}`)
export async function reviewApproval(poId:string,form:FormData){const user=await requireRole(['owner','admin']);const s=await createClient();const decision=value(form,'decision'),note=value(form,'review_note');if(!['approve','revision'].includes(decision)||(decision==='revision'&&!note))fail(`/approvals/${poId}`,'Pilih keputusan dan isi catatan revisi.');const{data:po}=await s.from('purchase_orders').select('*').eq('id',poId).single();if(!po||po.status!=='WAITING_APPROVAL')fail('/approvals','PO tidak menunggu approval.');const now=new Date().toISOString();await s.from('purchase_orders').update(decision==='approve'?{status:'COMPLETED',approved_by:user.userId,approved_at:now}:{status:'REVISION'}).eq('id',poId);await s.from('approval_requests').update({status:decision==='approve'?'approved':'revision_requested',review_note:note||null,reviewed_by:user.userId,reviewed_at:now}).eq('po_id',poId).eq('status','pending');if(decision==='revision')await s.from('revision_notes').insert({po_id:poId,note,annotated_attachment_id:value(form,'annotated_attachment_id')||null,created_by:user.userId});await s.from('activity_logs').insert({po_id:poId,actor_id:user.userId,action:decision==='approve'?'PO_APPROVED':'PO_REVISION_REQUESTED',metadata:{note}});revalidatePath('/approvals');redirect('/approvals?success=Review%20tersimpan.')}
export async function reopenPO(poId:string,form:FormData){const user=await requireRole(['owner']);const reason=value(form,'reason');if(!reason)fail(`/po/${poId}`,'Alasan wajib diisi.');const s=await createClient();const{data:po}=await s.from('purchase_orders').select('status').eq('id',poId).single();if(!po||po.status!=='COMPLETED')fail(`/po/${poId}`,'Hanya PO selesai yang dapat dibuka kembali.');await s.from('purchase_orders').update({status:'IN_PROGRESS',approved_by:null,approved_at:null,reopened_by:user.userId,reopened_at:new Date().toISOString(),reopen_reason:reason}).eq('id',poId);await s.from('activity_logs').insert({po_id:poId,actor_id:user.userId,action:'PO_REOPENED',metadata:{reason}});redirect(`/po/${poId}?success=PO%20dibuka%20kembali.`)}
